### ISSUE TITLE
SIGSEGV on quit when note is open

### ISSUE THREAD

**Issue by traumschule** [tomboy-notes/tomboy-ng#14]
Quit after using "Link" button results in SIGSEGV.

Version: 4cd7cb5b448fa48fb2edb96250f2ba87f1faa533
Architecture: i386
OS: debian stretch

```
TApplication.HandleException Access violation
  Stack trace:
  $08314336
  $08094143
  $08315884
  $08083C97
  $080822F6
  $08082320
  $08070A32
  $0807E66D
  $0807402D
Exception at 08314336: EAccessViolation:
Access violation.
```

# steps to reproduce
- open a note, mark text, click the "Link" button (without effect: #12)
- quit

**Comment by davidbannon** [comment]
How old was the checked out code when you saw this ? I have pushed code that fixes #12 (or so I hope) very recently. Check history.
D

**Comment by traumschule** [comment]
it's not fixed :( 
I posted the commit link above. Just pulled again and tested with version062df7b462de79c5d59d907bd2459d4bcffba834. Still quit causes a SIGSEGV on exit directly after clicking the "Link" button.

> Program received signal SIGSEGV, Segmentation fault.
> 0x08317f66 in TNOTELISTER__THISNOTEISOPEN (ID=0xb682ca2c '/home/hitchwiki/src/tomboy/Notes/b7963d4a-4953-4ae6-a456-09b654aed087.note', THEFORM=0x0, this=0x0)
>     at note_lister.pas:341
> 341             for Index := 0 to NoteList.Count -1 do begin
> #0  0x08317f66 in TNOTELISTER__THISNOTEISOPEN (ID=0xb682ca2c '/home/hitchwiki/src/tomboy/Notes/b7963d4a-4953-4ae6-a456-09b654aed087.note', THEFORM=0x0, this=0x0)
>     at note_lister.pas:341
> #1  0x08097d13 in TRTSEARCH__NOTECLOSING (ID=0xb682ca2c '/home/hitchwiki/src/tomboy/Notes/b7963d4a-4953-4ae6-a456-09b654aed087.note', this=0xb6b75c50)
>     at mainunit.pas:174
> #2  0x083194b4 in TEDITBOXFORM__FORMDESTROY (SENDER=0xb6b94e00, this=0xb6b94e00) at editbox.pas:581
> #3  0x08087867 in TCUSTOMFORM__DODESTROY (this=0xb6b94e00) at ./include/customform.inc:976
> #4  0x08085ec6 in TCUSTOMFORM__BEFOREDESTRUCTION (this=0xb6b94e00) at ./include/customform.inc:184
> #5  0x08085ef0 in TCUSTOMFORM__DESTROY (vmt=0x1, this=0xb6b94e00) at ./include/customform.inc:198
> #6  0x08070a32 in SYSTEM$_$TOBJECT_$__$$_FREE ()
> #7  0x08091f07 in TAPPLICATION__DOBEFOREFINALIZATION (this=0xb6b6e7b0) at ./include/application.inc:1093
> #8  0x0808223d in BEFOREFINALIZATION () at forms.pp:1904
> #9  0x0807402d in SYSTEM_$$_INTERNALEXIT ()
> #10 0xbffff62c in ?? ()
> #11 0xb7368276 in __libc_start_main (main=0x805f9f0 <main>, argc=1, argv=0xbffff624, init=0x83ab170 <_init_fini_dummy>, fini=0x83ab170 <_init_fini_dummy>,
>     rtld_fini=0xb7feb080 <_dl_fini>, stack_end=0xbffff61c) at ../csu/libc-start.c:291
> #12 0x083ab1c2 in SI_C21_$$__FPC_LIBC21_START ()

Note: When the note window is closed after clicking the link buton (which inserts no link #12), quit exists normally:

> Heap dump by heaptrc unit
> 517842 memory blocks allocated : 391015032/393557800
> 517842 memory blocks freed     : 391015032/393557800
> 0 unfreed memory blocks : 0
> True heap size : 425984
> True free heap : 425984
> [Inferior 1 (process 20486) exited normally]

**Comment by davidbannon** [comment]
OK (no, not OK), do you mind if I clarify ? Lets start in note "StartingNote" and 
1. You still do not see a new note pop up if you select text and click the link button ?
2. After doing above, if you exit tomboy-ng (quit menu from trayicon) immediately, you see this crash ?
3. If you close StartingNote first, the quit, no crash ?

Thanks, David

**Comment by traumschule** [comment]
Just found that is is not related to #12 but happens when any note is open on exit. Without open notes no crash.

**Comment by davidbannon** [comment]
yeah, me too ! 

Must be recent, I reckon when I added the code to ensure only one copy of a note. I obviously have not been testing from the console enough. I'm one it but need to go out soon....


David

**Comment by davidbannon** [comment]
Yes, fixed I hope. No real careful tests as under time pressure. An open note tells main unit when it opens and when it closes. However, during quit, the unit that mainunit stores that info may have gone down before hand. Info is irrelevent by then anyway so I just check if Notelister is valid before calling AlterNote() and ThisNoteIsOpen(). Seems OK....

But, related, is the Link button working as expected ?
