### ISSUE TITLE
Original tomboy vs tomboy-ng note text linking difference issue.

### ISSUE THREAD

**Issue by doninny** [tomboy-notes/tomboy-ng#260]
I had a few thousand notes in original tomboy. I've brought them over to tomboy-ng 0.34 and there is one difference between the 2 that is causing me a problem - the way text in notes is linked to other notes. Original tomboy used to link to the longest note title possible with found text, tomboy-ng seems to link tp the shortest. For example, suppose I have 2 notes with titles:

Widget
Blue Widget

And in another note I have the text: Acme is my favorite Blue Widget

Original tomboy would link the text to the "Blue Widget" note while tomboy-ng will display the Blue Widget text underlined as a link but when I click on the "Widget" part it it will actually link to the "Widget" note and when I click on the "Blue" part it will bring up a nonexistent note with the title "Blue_"

This is a major problem with my note taking strategy but also is the only real incompatibility issue I've seen, so thank you for carrying the tomboy fire into the future.

**Comment by davidbannon** [comment]
OK Doninny, that sounds bad.

I can replicate your problem so I will see what I can do !

Davo

**Comment by davidbannon** [comment]
Yeah, found it. Its a bug that has been there since day one !  I can and have fixed it but will need to do some testing before I let you have it, been some changes in significant part of the code.  Couple of days ....

Davo

**Comment by doninny** [comment]
Great, thank you for the update.

**Comment by davidbannon** [comment]
What operating system and 32/64 bit are you using doninny ?

Davo

**Comment by doninny** [comment]
Windows 10, 64 bit.     On Friday, April 15, 2022, 02:14:29 AM EDT, davidbannon ***@***.***> wrote:  
 
 


What operating system and 32/64 bit are you using doninny ?

Davo

**Comment by aguador** [comment]
I've note this problem as well, so if you want to build a 64-bit rpm version, I will give it a test.

**Comment by davidbannon** [comment]
OK, but I have spotted a problem during my testing, the "search while you type" feature has an issue so I needed to fix that. But playing in that space I spotted a potential place where I can speed it up so more alpha testing will be needed I am afraid. Should not be too long ...

Davo

**Comment by davidbannon** [comment]
OK, I have pushed out a 'fix' version, 0.43b, that fixes this problem. doninny, in your case, its tomboy-ng-setup-0.34b.exe. Roy, you know the system !

Now, these are not as well tested as I usually do before a release because I plan to add some (hopefully clever) patches that will deliver a very useful speedup for users with a lot of notes in the next couple of weeks. So, please be watchful and report anything that surprises you !

Davo

**Comment by doninny** [comment]
Ok my original example of Widget and Blue Widget now works (tomboy now correctly links to the Blue Widget) note but I still have a related issue.
I've reduced it down to the following example...

I deleted my original Widget and Blue Widget notes and created 2 notes with the following titles:
Widget
My Favorite Blue Widget

I copied the title from the "My Favorite Blue Widget" note into a 3rd note (as the only text on a line). Instead of linking the text to the "My Favorite Blue Widget" note it underlines and highlights in blue the Widget part and clicking on Widget brings up the Widget note.

**Comment by davidbannon** [comment]
Hmm, sounds like a similar variant of the same problem, I have probably made the same, wrong, assumption somewhere else.  I will need to dig in there a bit more, with your clear description, should not be too hard to find.
Thanks
Davo

**Comment by doninny** [comment]
The past 2 days I've been getting a popup error message I've never seen before popping up occasionally:

List index (###) out of bounds.

Where ### seems to be a different number each time.

**Comment by davidbannon** [comment]
Hmm, thats bad. Can you remember what you were doing when it happened ?

I have (finally) fixed the second part of the problem you reported here, turned out to be quite hard and I have had to rewrite a lot of the code that finds links in the notes. (And, sadly, the new code may be just a little slower). And thats an area where a list index is at risk. I'll be doing some more testing so, maybe I will see the problem you mention (or a new one!).

I hope to get a new test release out in the next few days.  Be really good if you could test it, especially for the list index problem. 

Davo

**Comment by doninny** [comment]
Not sure what's triggering the message. It's come up between 5 and 10 times in the last 2 days just when I was typing in some note. I'm unable to reproduce it on demand and I'm not sure what I might have been doing different that triggered it.  If I can produce the error on demand and track something down I will.

**Comment by doninny** [comment]
Maybe if you can give me some idea what a "List index" is that will help me reproduce the issue.

**Comment by davidbannon** [comment]
Hi Doninny, I know it looks bad but happening that frequently is, from my point of view good. It means when you start using the next beta, if it goes away, we know we have it fixed !

Sadly, bugs like that can be hard to locate unless I can reproduce it here and so far, I have not.

If it happens while you are typing in that note, it does sound to me like its the code that manages the links to other notes appearing. There are several 'lists' in there, I made a lot of changes in there, removing one sort of list and replacing it with another, lighter one. So, could be there but I have been hammering my test app here today and not seen any problems. Maybe its fixed in my new code. My new code has passed all its tests on Linux, I need to test on Windows and Mac yet but so far, looks good. So, expect it soon.

Incidentally, what operating system do you use ?

Davo

**Comment by doninny** [comment]
> Incidentally, what operating system do you use ?

Windows 10

**Comment by doninny** [comment]
For b there was a tomboy-ng-setup-0.34b.exe I installed but I don't seem to see a tomboy-ng-setup-0.34c.exe

**Comment by davidbannon** [comment]
Ah, sorry doninny, I have missed the Windows one while uploading. Its there now.
https://github.com/tomboy-notes/tomboy-ng/releases/download/v0.34/tomboy-ng-setup-0.34c.exe

Davo

**Comment by doninny** [comment]
Thanks! Looking good so far. If I run into any issues I'll report back.

**Comment by davidbannon** [comment]
OK, looks like this is certainly fixed in 0.35
So, I'll close
Thanks for the report.
Davo
